"""
Generate LaTeX-friendly assets (ROC coordinates, confusion matrix numbers)
from the trained cardio XGBoost model.

Runs on Windows without extra deps beyond the repo venv.

Usage:
  ..\\r1\\Scripts\\python.exe make_thesis_assets.py
"""

from __future__ import annotations

import json
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix, roc_curve
from sklearn.metrics import precision_score, recall_score, f1_score


def main() -> None:
    out_dir = Path("thesis_assets")
    out_dir.mkdir(exist_ok=True)

    df = pd.read_csv("ml_system/data/cardio_train_clean.csv", delimiter=";", low_memory=False)
    if "id" in df.columns:
        df = df.drop(columns=["id"])
    if "cardio" not in df.columns:
        raise SystemExit("Expected target column 'cardio' in dataset.")

    y = df["cardio"].astype(int).to_numpy()
    X = df.drop(columns=["cardio"])

    payload = joblib.load("ml_system/models/cardio_model.joblib")
    pipe = payload["pipeline"] if isinstance(payload, dict) and "pipeline" in payload else payload
    probs = pipe.predict_proba(X)[:, 1]

    # ---- Threshold trade-off curve (Precision/Recall/F1 vs threshold) ----
    thresholds = np.linspace(0.05, 0.95, 37)
    pr_coords = []
    rc_coords = []
    f1_coords = []
    for t in thresholds:
        pred = (probs >= float(t)).astype(int)
        pr = float(precision_score(y, pred, pos_label=1, zero_division=0))
        rc = float(recall_score(y, pred, pos_label=1, zero_division=0))
        f1v = float(f1_score(y, pred, pos_label=1, zero_division=0))
        pr_coords.append((float(t), pr))
        rc_coords.append((float(t), rc))
        f1_coords.append((float(t), f1v))

    thr_tex = (
        "% Auto-generated by make_thesis_assets.py\n"
        "\\addplot[color=CyberCyan, very thick] coordinates {\n"
        + "\n".join(f"  ({t:.3f},{v:.4f})" for t, v in pr_coords)
        + "\n};\n\\addlegendentry{Precision}\n\n"
        "\\addplot[color=ElectricIndigo, very thick] coordinates {\n"
        + "\n".join(f"  ({t:.3f},{v:.4f})" for t, v in rc_coords)
        + "\n};\n\\addlegendentry{Recall}\n\n"
        "\\addplot[color=CyberCyan!55!ElectricIndigo, very thick] coordinates {\n"
        + "\n".join(f"  ({t:.3f},{v:.4f})" for t, v in f1_coords)
        + "\n};\n\\addlegendentry{F1}\n"
    )
    (out_dir / "threshold_tradeoff.tex").write_text(thr_tex, encoding="utf-8")

    # ROC curve points (downsample for smaller TeX).
    fpr, tpr, _ = roc_curve(y, probs)
    step = max(1, len(fpr) // 120)
    coords = [(float(fpr[i]), float(tpr[i])) for i in range(0, len(fpr), step)]
    if not coords or coords[-1] != (1.0, 1.0):
        coords.append((1.0, 1.0))

    roc_tex = (
        "\\addplot[color=CyberCyan, very thick] coordinates {\n"
        + "\n".join(f"  ({x:.4f},{yy:.4f})" for x, yy in coords)
        + "\n};\n"
        + "\\addlegendentry{XGBoost (AUC=0.829)}\n"
    )
    (out_dir / "roc_xgboost.tex").write_text(roc_tex, encoding="utf-8")

    # Confusion matrix at threshold 0.5 (normalized by true class rows).
    preds = (probs >= 0.5).astype(int)
    cm = confusion_matrix(y, preds)
    cmn = cm / cm.sum(axis=1, keepdims=True)
    conf = {
        "tn": float(cmn[0, 0]),
        "fp": float(cmn[0, 1]),
        "fn": float(cmn[1, 0]),
        "tp": float(cmn[1, 1]),
        "counts": cm.tolist(),
        "rows": int(len(df)),
        "threshold": 0.5,
    }
    (out_dir / "confusion_xgboost.json").write_text(json.dumps(conf, indent=2), encoding="utf-8")

    # ---- XGBoost feature importance (top engineered/one-hot features) ----
    try:
        pre = pipe.named_steps["preprocessor"]
        model = pipe.named_steps["model"]
        names = list(pre.get_feature_names_out())
        importances = getattr(model, "feature_importances_", None)
        if importances is None:
            raise AttributeError("model has no feature_importances_")
        importances = np.asarray(importances, dtype=float)
        if len(importances) != len(names):
            raise ValueError("importance length mismatch")

        order = np.argsort(-importances)
        top_idx = order[:10].tolist()

        top = [(names[i], float(importances[i])) for i in top_idx]
        maxv = max(v for _, v in top) if top else 1.0

        def _pretty(n: str) -> str:
            # Convert "num__ap_hi" -> "ap_hi", "cat__cholesterol_2" -> "cholesterol_2"
            if "__" in n:
                n = n.split("__", 1)[1]
            # Use detokenize so underscores render without escaping.
            return "\\texttt{\\detokenize{" + n + "}}"

        labels = [_pretty(n) for n, _ in top]
        coords = [(i, 100.0 * top[i][1] / maxv) for i in range(len(top))]  # y index, scale 0-100

        fi_tex = (
            "% Auto-generated by make_thesis_assets.py\n"
            "\\begin{tikzpicture}\n"
            "\\begin{axis}[\n"
            "  width=0.92\\textwidth,\n"
            "  height=0.52\\textwidth,\n"
            "  xbar,\n"
            "  xlabel={Relative importance (scaled)},\n"
            "  y dir=reverse,\n"
            "  ytick={0,1,2,3,4,5,6,7,8,9},\n"
            "  yticklabels={"
            + ", ".join("{" + l + "}" for l in labels)
            + "},\n"
            "  yticklabel style={font=\\scriptsize, align=right},\n"
            "  xticklabel style={font=\\scriptsize},\n"
            "  grid=major,\n"
            "  bar width=9pt,\n"
            "  nodes near coords,\n"
            "  nodes near coords style={font=\\scriptsize},\n"
            "  title={Top Features by XGBoost Importance},\n"
            "  font=\\small,\n"
            "]\n"
            "\\addplot[fill=CyberCyan!35, draw=DeepObsidian] coordinates {\n"
            + "\n".join(f"  ({v:.1f},{k})" for k, v in coords)
            + "\n};\n"
            "\\end{axis}\n"
            "\\end{tikzpicture}\n"
        )
        (out_dir / "feature_importance_xgb.tex").write_text(fi_tex, encoding="utf-8")
    except Exception:
        # Not fatal; the thesis can compile without this optional asset.
        pass

    print(f"Wrote: {out_dir / 'roc_xgboost.tex'}")
    print(f"Wrote: {out_dir / 'confusion_xgboost.json'}")
    print(f"Wrote: {out_dir / 'threshold_tradeoff.tex'}")
    print(f"Wrote: {out_dir / 'feature_importance_xgb.tex'}")


if __name__ == "__main__":
    main()
